disabled_rules: # rule identifiers to exclude from running
  - colon
  - control_statement # we would need this the other way around
  - nesting
  - variable_name_max_length
  - variable_name
  - todo

#included: # paths to include during linting. `--path` is ignored if present. takes precendence over `excluded`.
#  - Core
#  - DKExtensionsSwift
#  - Submodules
#  - Helpers
#  - Classes

excluded: # paths to ignore during linting. overridden by `included`.
  - Carthage
  - Pods
  - External

# rule parameters
file_length:
  - 600 #warning
  - 800 #error

function_body_length:
  - 40 #warning
  - 80 #error

line_length:
  - 300 #warning
  - 350 #error

type_body_length:
  - 400 #warning
  - 500 #error

####### enabled rules #######
#  - comma
#  - file_length
#  - force_cast
#  - force_try
#  - function_body_length
#  - leading_whitespace
#  - legacy_constructor
#  - line_length
#  - opening_brace
#  - operator_function_whitespace
#  - return_arrow_whitespace
#  - statement_position
#  - trailing_newline
#  - trailing_semicolon
#  - trailing_whitespace
#  - type_body_length
#  - type_name
#  - valid_docs
#  - variable_name_min_length
